title: Мое Портфолио Игр
description: Коллекция моих проектов по разработке игр
author: Дмитрий Н.Р.
url: "https://ВАШЕ_ИМЯ_ПОЛЬЗОВАТЕЛЯ.github.io" # Замени на свой URL
baseurl: "" # Оставь пустым для пользовательских страниц, или "/ИМЯ_РЕПОЗИТОРИЯ" для страниц проектов

# Настройки Jekyll
markdown: kramdown
theme: jekyll-theme-minimal # Можешь выбрать другую тему или создать свою

# Добавь коллекцию для проектов, если хочешь более сложной структуры
# collections:
#   projects:
#     output: true
#     permalink: /projects/:name/

# Настройки для тегов (для более продвинутой реализации тегов)
# tags:
#   output: true
#   permalink: /tags/:name/
